### PR TITLE
postprocessors can have context

### PR DESCRIPTION
**Pull request by jlarsson**
I short, its possible to pass an optional context to Parser:

```
// js
var context = {foo: function (d) { ... }}
var p = new nearley.Parser(grammar.ParserRules, grammar.ParserStart, context)

...
// grammar
rule -> a b c {% function (d) { return this.foo(d) } %}
```

The motivation is that it in general makes it easier to construct more semantically bound ASTs and in particular allows complex logic to separated from the grammar specification.

I made some changes to the test structure:
- existing tests are now pre tests
- added unittests using mocha

Thanks for a great piece of work ;)

### CODE REVIEW

**Comment by JacobEdelman** [comment]
This definitely seems rather useful. Hardmath123 is currently on vacation but he'll be back in a couple of weeks.

**Comment by rwindelz** [comment]
@jlarsson I understand the wish to abstract the AST constructors; it can be quite handy.  Would you compare & contrast this idea of a context with the code blocks that Nearley already supports.
ie. 
`prod -> word whit? ("-"|"="):+ ">" whit? expression+  {% function(d) { return {name: d[0], rules: d[5]}; } %}
      | "@" whit? js  {% function(d) { return {body: d[2]}; } %}
`
In particular, the `"@" whit? js` which allows you to include arbitrary function definitions
eg.
`@ {% var id = function (d) { return d; } %}
`

**Comment by jlarsson** [comment]
(_apologies for ranting_) @rwindelz Code blocks are unfortunately not comparable to fully externalized contexts.
* Code blocks are an implementation, while the context acts as an api (from the grammar perspective)
* Code blocks are maintained along with the grammar while contexts can reside anywhere and can benefit from unittests, linters and other JS centric methodologies
* Code blocks kind of often forces parsing results to have the form of the lowest common denominator, while contexts can be made arbitratily specific to the desired task. Lets use the calculator grammar as an example. It would require a substantial rewrite of that grammar to have a parsing return a syntax tree. On the other hand, its not hard to feed the parser with a AST factory (the context) which in one implementation performs direct evalutation and in another builds a syntax tree. The language (the grammar) stays the same, but the interpretation of sentences spoken in that language is left to application.

In OO terms, grammars can now adapt the Single Responsibilty Principle (i.e. it knows syntax but nothing else) and the Open Closed Principle (grammar stays fixed but added context implementations can produce new interesting results).
These are (for me) crucial values when development of a parser matures from a simple pipeline tool into a mission critical business value.

**Comment by JacobEdelman** [comment]
I have to agree that there are many times where contexts of this type would have been useful.

**Comment by rwindelz** [comment]
@jlarsson  We have different ideas on what is a rant :-)  I appreciate the clarity of your explanation.
Regarding your bullets.  On point 1 I am ambivalent, perhaps only because with some discipline using code blocks you may achieve something similar.  On point 2 & 3 I absolutely agree.

Many parser implementations clutter up the grammar specification with actions / semantics and while the semantics are required to do anything useful with the parse, the penalty with respect to the clarity of the grammar specification is high (too high in many cases - my personal feeling on this).

Out of general interest I keep an eye on the activities at http://vpri.org/ in particular the work done by Ian Piumiarta and Alessandro Warth ( @alexwarth ).  Of particular interest has been OMeta and now https://github.com/cdglabs/ohm.  Of note in Ohm is the notion that the grammar should be specified [without the semantics](https://github.com/cdglabs/ohm/blob/master/doc/philosophy.md).    The semantics in Ohm are injected later just as you are proposing here (for the same reasons).  I can recommend https://github.com/cdglabs/ohm/blob/master/examples/math/index.html where you should see striking similarities with your contexts.  OMeta & Ohm do have one deal breaker for me in that they are based on PEG with its ordered choice requirement.
I like the clean look of the Ohm grammars and the fact that the host language does not appear in the grammar specification.  Nearley with contexts still has a host language component in the grammar specification however it would be a small change to the grammar to do the equivalent of Ohm.  (at the same time I would drop code blocks as they are subsumed by contexts)

**Comment by jlarsson** [comment]
Thanks for the reading references :)
As much as I strive for separation between grammar and semantics, my pragmatic angle is that code blocks and contexts are highly complementary.

If postprocessors where left only to simply delegate to context methods, code blocks are obviously redundant. But (again, this is my opinion based on my coding style), postprocessors are best when they can offer some utility - typically fixes to grammar ambiguity or just patching otherwise hard to express grammars. The examples that comes to my mind are 
* trivial reductions: reducing terminals before passing on to context (joining _[a-z]:+_ and such)
* hiding grammar structure: (programming) languages are noisy;  keywords, punctuations, whitespace and what else. The inlined postprocessor does the selection of which sub parsings to pass along to the context. This issue might be less relevant with _named tokens_ (#58), but the key point is that _semantics must be decoupled from actual grammar structure_.
* early rejection: my personal style would be to (at least try) reject early in inlined postprocessor code instead of delegating that decision to the context. I think. Its still a hypothetical question for me and the need for it might be an indication of ~~sloppy~~ unwanted side effects in semantic actions...

In Ohm (if I understood it correctly), the semantic part must be fully aware of every grammar detail, and you are essentially writing down your productions again, albeit in another form. I strongly object to this anti pattern (duplicate code). 

Ohm has one big advantage  though - semantic actions are invoked exactly once and never for rejected derivations. But that is a property of PEGs (which kills ambiguity) and not really a consequence of how Ohm evaluates semantics.

**Comment by rwindelz** [comment]
re: my dropping code blocks comment
sorry, i mistakenly said 'drop code blocks' when i was thinking specifically of the code blocks that are not attached to any rule, ie, `"@" whit? js {% function(d) { return {body: d[2]}; } %}`

re: the anti pattern of duplicate code
It's not really duplicate code in that while grammar and semantics are isomorphic, one disassembles and the other reassembles.  Think of fold/unfold in algebraic data types; the grammar unfolds the input tokens into the abstract datatype and the semantic function folds the abstract datatype to produce the meaning value.   You have a choice of interleaving the specification or factoring apart.  If you allow for specification in either the grammar or the semantics then the reader may have to consult two separate documents to understand.

The Earley algorithm also has a property that for any specific start position in the input stream the semantic actions for any non terminal will only be invoked once with the caveat that for right recursive grammars a small change to the algorithm (that subsumes [Joop Leo's](http://www.sciencedirect.com/science/article/pii/030439759190180A)) is required.  The semantic actions will only be invoked once for each parse result returned.  This effectively memoizes intermediate parse results across ambiguous parses.  To defer evaluation, wrap results in lambdas.

cheers

**Comment by Hardmath123** [comment]
Hi there! Thanks for taking a look at nearley.

I'm a little concerned that this doesn't actually add any functionality that nearley doesn't already have. You can do something like

```
@{% var ctx = require("context.js");  %}
# …
# …
a -> something something complicated grammar {% ctx.foo %}
```

As such, I'm not too worried about separating grammar from postprocessor functionality—nearley is a JavaScript-based parser and so it doesn't need to be language-agnostic.

**Comment by jlarsson** [comment]
@Hardmath123 Binding to a module using `require` is entirely different (and strictly weaker in an OO perspective) from invoking actions in a truly dynamic/polymorphic context.
You are advocating globals, I'm more in for separation of concerns.

**Comment by Hardmath123** [comment]
I'm not sure separation is the best choice in this case. It's really a question of what you want from your parser, and I don't think a parser should do too much. Postprocessors shouldn't have any complex logic in them; that should almost always be left up to the code that will interpret the AST. Part of the appeal of describing a language as syntax + semantics is that the two halves can be mutually agnostic.

Maybe it would be more convincing to me if you showed a use case where providing this "context" object would be substantially nicer?

**Comment by jlarsson** [comment]
In unit testing or any other situation where I want to have explicit/special/different semantic interpretation of a parsing,

**Comment by Hardmath123** [comment]
Sorry, lost track of this discussion for a bit because of school and stuff.

Rereading the discussion, it seems like an alternative solution, that has all of the benefits you described, would be to produce a "global" variable `$ctx` or something which contains all the "context". I think that would be a nicer solution because using `this` requires you to create a `{% function(d) {this.makeTree(d); } %}`, whereas with the global variable we can write post-processors as `{% $.makeTree %}`. Additionally, I would like to reserve the `this` binding for some other purpose in the future—maybe meta-information about the parse.

Finally, it feels weird having the mocha test for just this one feature. Could we just write a simple test-case in the `test/` directory, along with the remaining tests?

Thanks, and sorry again for the 1.6 month delay…

**Comment by jcorbin** [comment]
Hmm, also if you're going to do anything to introduce more standardized testing, I'd recommend using https://github.com/substack/tape instead of mocha.

**Comment by solmsted** [comment]
This is an older discussion, but for what it's worth, I really like the idea of being able to pass in some data that postprocessor functions can use.  I think it would work better if it was passed as an argument to the function instead of using `this`.

**Comment by Hardmath123** [comment]
Mmm, okay, so this branch apparently has merge conflicts but let's see if either @jlarsson or I can get it up-to-date and merged for @solmsted to use. :-)

Oh, and I like the idea of it being an argument rather than `this`… it seems more natural to me. Perhaps we can make `this` point to the parser itself (if it doesn't already)?

**Comment by nanalan** [comment]
For those that really need this feature, [nearley-make](https://github.com/nanalan/nearley-make#usage) supports passing arguments to your grammar (second argument to `make`). It's not a perfect solution, but it works :smile:

**Comment by vietlq** [comment]
Any update here?

**Comment by tjvr** [comment]
It's an interesting idea. It won't happen anytime soon but we'll think about it for v3. :-)

**Comment by Hardmath123** [comment]
Closing this PR — I doubt this will be actually useful, and it has too many merge conflicts.

**Pull request closed without merging**
