### PR TITLE
Better compile prep

### PR DESCRIPTION
**Pull request by jcorbin**
Superficial prep work out ahead of compiler embetterment.

### CODE REVIEW

**Comment by jcorbin** [comment]
Over the course of this and subsequent PRs, it may help to peak ahead at https://github.com/Hardmath123/nearley/compare/Hardmath123:master...jcorbin:better_compile for larger "where are we going with this again?" context; final commit on that branch has a rough plan of how I plan to carve up said PRs.

**Comment by Hardmath123** [comment]
Looks good. Before I merge, though: something weird happened to the indentation of `nearley-language-bootstrapped.js`. Could you check on that?

P.S. TIL about bash's brace expansion. Neat stuff. :-)

**Comment by jcorbin** [comment]
So funny story about that indentation: it just so happened that where joiner and arrconcat were defined previously just happened to line up well with the indentation level needed by `lib/generate.js`'s output.

Now, I'm all for changing generate to always get that indent right... sounds like another PR ;-)

**Comment by jcorbin** [comment]
Will block on merging #71, then rebase this PR for less churn.

**Comment by jcorbin** [comment]
Rebased, turns out we still missed edge case from #73, fixed in the first commit of this branch now.

**Comment by Hardmath123** [comment]
Thanks, merging. :-)

**Pull request merged**
