### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by tjvr**
@Hardmath123 I hope you don't mind me doing this. :-)

This is a small, friendly PR that does the following:

* Use `expect()` instead of `should` for the tests.
* Refactor the tests a little bit (particularly the code in `_shared.js`).
* Clean up the temporary files after the external tests are done. This stops the tests from sometimes passing when they really shouldn't have!

### CODE REVIEW

**Comment by Hardmath123** [comment]
Err, I merged your other PR and now this one has conflicts. :-/

**Comment by tjvr** [comment]
Yeah, don't worry--I'll fix those. :-)

**Comment by tjvr** [comment]
All fixed :-)

**Comment by tjvr** [comment]
(I read your message as implicit approval; apologies if that was wrong of me!)

**Pull request merged**
