### PR TITLE
Better named sub rules

### PR DESCRIPTION
**Pull request by jcorbin**
This makes it easier to follow generated code from the compiler.

### CODE REVIEW

**Comment by jcorbin** [comment]
Also re-bootstrapped the language for a demo of why this is easier to read.

**Comment by jcorbin** [comment]
Not sure if you want `test/{ebnf,negatable}.js` also re-genned.

**Comment by jcorbin** [comment]
Note: this PR is the tip of a larger working branch where I'm coming to terms with your compiler: https://github.com/Hardmath123/nearley/compare/Hardmath123:master...jcorbin:better_compile

Let me know how interested you are in further improvements here, I can start decomposing that branch into more digestable stages in subsequent PRs.

**Comment by Hardmath123** [comment]
Very nice. This was one of those little hacks that bothered me but I never had motivation to fix… thanks for doing this.

I would love more improvements to the core compiler. And yeah, it would be *amazing* if you could break it up into separate easy-to-review PR's, but if that's too much work, then don't worry too much about it. :-)

**Pull request merged**
