### PR TITLE
Added generation of TypeScript code

### PR DESCRIPTION
**Pull request by heatherleaf**
Here's another code generator, similar to Coffeescript, but this time it's for TypeScript: http://www.typescriptlang.org

### CODE REVIEW

**Comment by tjvr** [comment]
Is this useful, given that nearley doesn't have TypeScript annotations?

**Comment by Hardmath123** [comment]
Looks okay to me, and I'd be happy to merge it if you have a use-case for it.

Just a quick note, though: I think `type NearleySymbol = string | {literal:string};` is not quite accurate. The real type is more like: `string | {literal: any} | {test: _ => Boolean}` (I'm unfamiliar with typescript's exact syntax, sorry). Similarly, the type of postprocessor functions should have three arguments, not just one (something like `(d:any[], loc:number, reject:{})=>any`).

**Comment by heatherleaf** [comment]
Thanks for your positive replies!

The use case is the Shrdlite course project (that you mention first in your list of projects using Nearley). The project is written in TypeScript, and with a direct TS generation from Nearley, it's easier to use it with existing TS code (because you don't have to write a `.d.ts` file).

See the github project: https://github.com/ChalmersGU-AI-course/shrdlite-course-project; the files to look at are `Grammar.ne`, `Grammar.ts` and `Types.ts`. The last file contains type declarations that are used in the grammar. The grammar is then used in the file `Parser.ts`.

To use it you still need the file `lib/nearley.d.ts`, which contains type declarations for the nearley parser. If you want you can add that file to Nearley as well (together with a short instruction on how to use it in TypeScript).

**Comment by heatherleaf** [comment]
Thanks for the explanation of the types. I'll look into them and update my pull request.

**Comment by Hardmath123** [comment]
Thanks for the update! I've merged the PR, and it should be updated on npm as well.

P.S. Shrdlite is by _far_ my all-time favorite nearley project. :-)

**Comment by heatherleaf** [comment]
Thanks for that! Btw, the GitHub name of the project has changed, now it is:

https://github.com/ChalmersGU-AI-course/shrdlite-course-project

**Comment by Hardmath123** [comment]
Got it — I updated links on the README and on the webpage.

**Comment by SmaugTheGreat** [comment]
This isn't working for me. Using `@preprocessor typescript` gives me an error:

```
[...]\node_modules\nearley\lib\generate.js:18
    var lines = func.toString().split(/\n/);
                    ^

TypeError: Cannot read property 'toString' of undefined
    at dedentFunc ([...]\node_modules\nearley\lib\generate.js:18:21)
    at serializeRule ([...]\node_modules\nearley\lib\generate.js:92:53)
    at [...]\node_modules\nearley\lib\generate.js:13:14
    at Array.map (native)
    at serializeRules ([...]\node_modules\nearley\lib\generate.js:12:30)
    at Function.generate.ts.generate.typescript ([...]\node_modules\nearley\lib\generate.js:178:37)
    at generate ([...]\node_modules\nearley\lib\generate.js:107:48)
    at StreamWrapper.<anonymous> ([...]\node_modules\nearley\bin\nearleyc.js:52:22)
    at emitNone (events.js:91:20)
    at StreamWrapper.emit (events.js:185:7)
```

**Comment by Hardmath123** [comment]
Looks like a bug — could you open a separate issue, in which you (1) make sure you have the latest versions of nodejs and nearley, and (2) show us what you're trying to compile? Thanks.

**Pull request merged**
