### PR TITLE
The Great Compile Breakup

### PR DESCRIPTION
**Pull request by jcorbin**
Breaks each token builder out, makes rule and token building more functional.

### CODE REVIEW

**Comment by jcorbin** [comment]
I ended up putting more into this PR than I first thought I would, let me know if you'd rather this one be dialed back more.

I strongly suggest ignoring whitespace to review this PR (add `?w=1` to github, or just use git with `-w` git option).  You may also find it easier to review commit a time.

**Comment by Hardmath123** [comment]
Looks good, but I won't be able to review/merge things until the week-end because of school and stuff. :-)

**Comment by jcorbin** [comment]
Weekend bump ;-)

**Comment by Hardmath123** [comment]
Very nice, thanks so much.

Out of curiosity, why did you prefer `for` instead of `[].forEach` in 9ab912e? Is there a performance issue, or is it more of a stylistic choice?

**Comment by jcorbin** [comment]
Yeah, for loops are indeed substantially faster than a forEach when it matters.  Also trying to use a network of high level functions (forEach, map, reduce, filter, etc) tends to be much harder to understand in larger combination than simple for loops and such.

**Pull request merged**
