### PR TITLE
Quiet

### PR DESCRIPTION
**Pull request by sandiegoscott**
Omit ANSI color codes in quiet mode.

### CODE REVIEW

**Comment by sandiegoscott** [comment]
Okay, I didn't merge your latest master before pushing this PR as I undoubtedly should have. Shall I close this one and issue another correctly?

**Comment by bobbybee** [comment]
@Hardmath123 mentioned that printing the results header should be conditional based on --quiet as well.

**Comment by Hardmath123** [comment]
Looks good. Thanks!

**Comment by Hardmath123** [comment]
[Our masters were aligned, so no issues with git. :-) ]

**Pull request merged**
