### PR TITLE
Generate static site for docs

### PR DESCRIPTION
**Pull request by tjvr**
@Hardmath123 I wrote that site generator for you!

A separate `package.json` is provided in `docs/` for you. Run `npm install && npm start` from inside that folder; then you can view the docs locally. `npm run make` rebuilds 'em from the Markdown files.

### CODE REVIEW

**Comment by tjvr** [comment]
There's now a navigation sidebar (which just sits at the top of the page on mobile).

**Comment by tjvr** [comment]
After merging this, we should:

- Add a prominent link to <https://nearley.js.org/docs/> from the README and the homepage.
- Remove documentation from the README and `docs/index.md`, and add it into separate `docs/` pages.
- If you like, we can add prev/next links, and add some kind of non-alphabetical ordering to the pages. :-)

**Comment by tjvr** [comment]
After merging this, we should:

- Add a prominent link to <https://nearley.js.org/docs/> from the README and the homepage.
- Remove documentation from the README and `docs/index.md`, and add it into separate `docs/` pages.
- If you like, we can add prev/next links, and add some kind of non-alphabetical ordering to the pages. :-)

**Comment by Hardmath123** [comment]
Thanks, Tim!

**Comment by Hardmath123** [comment]
Err, the main "tutorial" has a page title of "Installation" now. Is this intentional? Are you planning on breaking this up into sub-sections or something?

**Comment by tjvr** [comment]
@Hardmath123 No, that was a mistake!

**Comment by tjvr** [comment]
(I converted the top-level h2s into titles. That file had more than one h2, so I shouldn't have done that)

**Comment by tjvr** [comment]
Yes, we should split the index into separate pages. I'm hoping you'll do that, since you're better at docs. :-)

I think we should aim to just cut out bits of the README / move them into docs, and leave the rest as-is. Maybe expand the 1,2,3 example to use a slightly more serious grammar?

Which file is used for nearley.js.org? Right now the body appears to have the docs-page class on it, which it shouldn't (it makes space for the sidebar).

I also need to add the meta viewport tag for mobile support, but I can commit that straight to master.

**Comment by Hardmath123** [comment]
nearley.js.org is index.html in root. We should ideally convert it to markdown and use _that_ as docs/index.html. We'd basically get rid of /www altogether — there's an option for Github pages to serve everything from /docs as the root.

**Comment by tjvr** [comment]
> there's an option for Github pages to serve everything from /docs as the root.

Great idea.

**Comment by tjvr** [comment]
> we should split the index into separate pages

did some of this--see #272. :-)

Still need to cut up the `README` and `/index.html`.

**Pull request merged**
