### PR TITLE
Fix generate indent

### PR DESCRIPTION
**Pull request by jcorbin**
As discussed on #71, this fixes `lib/generate.js` so that it outputs more consistent output.

The churn in `lib/nearly-language-bootstrapped.js` is due to now correctly stripping leading space from function#toString output.

### CODE REVIEW

**Comment by Hardmath123** [comment]
Shiny.

I think the `dedent` solution is very clever, but I think it might fail in a couple of pathological cases such as

```
a -> "foo" {%
function (x) {
    return x;
             }
%}
```

Maybe you want to "dedent" by the minimum number of leading spaces in `lines[1:]` (Python slice syntax?) rather than the number of leading spaces in the last line, which is how I understand it works right now.

If you think that's messy, though, I'm happy to merge as-is. Your call.

**Comment by jcorbin** [comment]
Good call, changed to take min indent over the tail; verify no change under `npm run bootstrap`.

**Comment by Hardmath123** [comment]
One of the lines in the diff seemed duplicated; is this a typo or am I missing something?

**Comment by jcorbin** [comment]
Fixed the derplicated line.

**Comment by Hardmath123** [comment]
Nice, merged. Thanks. :-)

**Pull request merged**
