### PR TITLE
Make things Faster!

### PR DESCRIPTION
**Pull request by tjvr**
This is a PR to track some of the work I'm doing on rewriting nearley's internals :-)

### CODE REVIEW

**Comment by tjvr** [comment]
So far this isn't as dramatically faster as I'd hoped for.

However, this might just be because I'm not looking at the right sort of benchmarks. Currently I'm using the test runs as a proxy for performance, which isn't terribly informative! Ideally I'd test this on a large tosh grammar with a tokenizer in front of it, perhaps. :)

**Comment by bd82** [comment]
See a previous issue related to performance.
https://github.com/Hardmath123/nearley/issues/111

I've used (and linked) a few benchmark pages there using nearley & JSON Grammar
plus 1,000 lines JSON input.

You can also use the main benchmark pages which compares relative performance
of different JavaScript Parser Generators/Toolkits/Combinators.
http://sap.github.io/chevrotain/performance/

The UX there allows selecting only the parser toolkit you want.
And it also includes a link to the github repo so you can just clone it locally, modify the code (load different nearley.js file) and run it by opening the performance/index.html file.

**Comment by bd82** [comment]
For advanced optimizations also try
IRHydra
http://mrale.ph/irhydra/2/

It is a tool which helps you figure out de-optimization reasons under V8 engine.
It was very useful when I've performed performance optimizations in the past.

**Comment by tjvr** [comment]
@bd82 No thanks. JSON is not a useful benchmark.

**Comment by bd82** [comment]
> JSON is not a useful benchmark.

Why not?

Obviously it does not cover the full scope of Nearley capabilities as it is a very simple
grammar which only requires LL(1) and does not have ambiguities or left recursion.
So it can only be **part of** a benchmark suite not the whole suite.

But it has alternation, repetition and production nesting. These rules are probably enough
to describe the Python programing language which is also LL(1) as it is a [design goal](https://www.python.org/dev/peps/pep-3099/) of python.

It is also simple to implement so you can easily compare Nearley performance to other parsing toolkits or even compare to hand built JSON parsers.

If you can get a simple grammar to be faster won't that influence the more complex ones too?

**What would you define as a useful benchmark?**

**Comment by tjvr** [comment]
@bd82 This is not the right place for this conversation, sorry.

**Comment by tjvr** [comment]
Actually, this is a pretty compelling set of improvements:
```sh
$ git checkout master
$ node test/benchmark.js 
  ✔ calculator arithmetic2 x 776 ops/sec ±2.45% (84 runs sampled)
  ✔ json test2.json x 325 ops/sec ±0.36% (88 runs sampled)
  ✔ tosh ex1 x 37.43 ops/sec ±0.56% (63 runs sampled)
$ git checkout opt
$ node test/benchmark.js 
  ✔ calculator arithmetic2 x 1,910 ops/sec ±4.61% (84 runs sampled)
  ✔ json test2.json x 705 ops/sec ±0.55% (86 runs sampled)
  ✔ tosh ex1 x 342 ops/sec ±1.46% (84 runs sampled)
Done in 17.40s.
```
* The calculator benchmark is ~2x faster
* The json benchmark is ~2x faster
* The tosh benchmark is nearly an order of magnitude faster! (This PR focuses on large grammars, so this is not surprising.)

Bear in mind these are only small examples. :)

**Comment by tjvr** [comment]
However, I don't think this is quite mergeable yet; I think it may still have some bugs we need to track down...

**Comment by tjvr** [comment]
I'm a lot more confident about this now I've tracked down #180. (Although I'm still a little confused as to why this PR seems to cause nearley to use more memory!)

**Comment by tjvr** [comment]
I added a commit 85ca34b that GCs unused states :D
Since State now keeps track of the states that predicted it -- the `wantedBy`
attribute -- states which are or may be part of the final parse are always
kept.

When we support rewind(), we'll have to make this optional (based on a `{ rewindable: true }` option given to Parser?)

You can see the difference if you run `node test/profile.js`.

**Comment by tjvr** [comment]
I think this is good now @Hardmath123 -- want to take a look at some point? :)

**Comment by bd82** [comment]
Tested this on a 45K (1,000) lines JSON.
Using the lexerless JSON grammar example (minus the grammar actions).

with 2.7.14 I got around 1.3 ops/second.
with 2.7.14 + these optimizations I got 4.71 ops/second.

so very very nice 👍

**Comment by tjvr** [comment]
@bd82 Thanks for testing :-)

I'd be very interested to see how this affects your JSON plus lexer parser. :-)

**Comment by bd82** [comment]
I will try to test tomorrow.

**Comment by bd82** [comment]
With Tokenizer:

About **40 Ops**/second with **both** 2.7.13 and 2.7.14
With 2.7.14 + these optimizations: about **95 Ops**/second.

👍

**Comment by bd82** [comment]
### Suggestion for possible optimization:
The [State Object](https://github.com/Hardmath123/nearley/blob/3b415764680df370317f1de3519bf45263a3b5fa/lib/nearley.js#L35) is initialized using the **"new"** keyword.

I'm not sure if this will help, but I have seen improvements in similar scenarios when
using more basic structures, I.E:
```
var state = {rule:X, expect:Y, reference:Z, data:[]}
```
and instead of putting the methods on the State Prototype:
```Javascript
State.prototype.consumeNonTerminal = function(inp) {...}
```
Using standard functions which accept the state object:
```Javascript
function consumeNonTerminal(inp, state) {...}
```
I tried doing it myself but messed up the refactoring and ended up with an infinite loop.
I may find time later this week to try again. But you may have better luck trying this
(assuming that hopefully it would help).

**Comment by tjvr** [comment]
@bd82 Thans for benchmarking with the tokenizer! (I tried it myself but couldn't get it to work :-) )

**Comment by tjvr** [comment]
I decided this still wasn't fast enough, so I bring you 7fc11d4 :
```
  ✔ calculator arithmetic2 x 3,918 ops/sec ±1.97% (81 runs sampled)
  ✔ json test2.json x 1,636 ops/sec ±1.53% (86 runs sampled)
  ✔ tosh ex1 x 448 ops/sec ±1.29% (86 runs sampled)
```

**Comment by Hardmath123** [comment]
:D

**Comment by tjvr** [comment]
:D :D

**Comment by cmcaine** [comment]
I get slightly better performance with chevrotain's benchmark on e96a532 than on v2.11 (~68ops/s vs ~55 ops/s)

I don't get anywhere near 1000 ops/s. Presumably you and bd82 are measuring different ops? Maybe because bd82's json is so huge?

My mirror of the performance page (uses v2.11): https://cmcaine.github.io/chevrotain/performance/

**Comment by bd82** [comment]
Yes @cmcaine.

There is not much point in comparing **absolute** ops/second over **different** machines and **different** inputs.

It is the **relative** performance numbers that are actually meaningful.

**Comment by cmcaine** [comment]
Yes, of course :)

I wanted to highlight a possible performance regression in nearley 2.11 compared to this PR.

**Comment by tjvr** [comment]
> a possible performance regression

If you think you've found one -- our preferred benchmarks can be run using `npm run benchmark`, btw -- then please open a new issue. :-)

**Comment by cmcaine** [comment]
The benchmarks are dissimilar and I can't compile the new version of json.ne at this commit:

```
in nearley on e96a532...
› git tag faster

in nearley on tags/faster
› npm install && npm install moo

in nearley on tags/faster
› git checkout master examples/json.ne

in nearley on tags/faster
› ./bin/nearleyc.js examples/json.ne | node
[stdin]:78
    {"name": "number", "symbols": [number], "postprocess": function(d) { return parseFloat(d[0].value) }},
                                   ^

ReferenceError: number is not defined
```

Running sample1k.json through the old json.ne gives ~9 op/s, but there's no lexer on that.

**Pull request merged**
