### PR TITLE
Split up docs/index some more

### PR DESCRIPTION
**Pull request by tjvr**
Yo @Hardmath123. This splits out all the main index sections into their own chapters -- and then pulls in related bits, to fill out each chapter a bit more.

Have a look at the commits for more details. :-)

### CODE REVIEW

**Comment by Hardmath123** [comment]
Oh no! Merge conflicts!

**Comment by Hardmath123** [comment]
Perhaps the files should be `compiler.html` and `parser.html` instead of "language" and "usage", which are kind of confusing?

**Comment by tjvr** [comment]
I don't like the name "compiler" (I think it gets confusing calling `nearleyc` a compiler). Perhaps `ne-syntax` and `parser`?

**Comment by Hardmath123** [comment]
> I think it gets confusing calling nearleyc a compiler

Yeah, even though that's really what it is — a syntactic-sugar-expander. It's confusing because we use a grammar to make a parser to parse a grammar for grammars that make other parsers.

Maybe `grammar` and `parser`?

**Comment by tjvr** [comment]
Merged & renamed!

**Pull request merged**
