### PR TITLE
add positive decimals to builtins

### PR DESCRIPTION
**Pull request by seiyria**
there are positive integers, I think positive decimals should be added for consistency

### CODE REVIEW

**Comment by Hardmath123** [comment]
Mmm, interesting. See, looking at this more carefully, it makes sense that what is currently `int` should actually be called `unsigned_int`, and `posdecimal` should actually be called `unsigned_decimal`.

So, two questions.

1) Do you have an actual use-case for `unsigned_decimal`, or is it literally just for consistency?
2) Would you be willing to update the PR, renaming `pos_…` to `unsigned_…`?

Thanks!

**Comment by seiyria** [comment]
I do have a use case. In my project, my language has a few variables pulled
out that represent offsets that can't be negative.

I'd be willing to update the pr. I can do it tomorrow if you want to merge
it. Will you also be updating the int to match with that release?

**Comment by Hardmath123** [comment]
Yeah, updating int would be nice as well.

Thanks!

**Comment by seiyria** [comment]
@Hardmath123 done! :D

**Comment by bobbybee** [comment]
@seiyria I suspect you'll run into bugs anyway if you drop a variable for the offset... which you should support..

**Comment by seiyria** [comment]
@bobbybee I'm not sure I follow what you mean. With the language I'm building, variables only exist as part of loops, and when using a loop you can only iterate from 0 to a number. It's intentionally restrictive and should be manageable.

**Comment by Hardmath123** [comment]
Thanks @seiyria ! This is great; I've merged it into master, and you'll be able to use it in the next release of nearley (or you could start using it now by installing nearley from the git repository).

**Comment by seiyria** [comment]
Awesome! When will you be releasing the next version?

**Comment by Hardmath123** [comment]
It should be online now.

**Comment by seiyria** [comment]
Great, thanks again!

**Pull request merged**
