### PR TITLE
Remove unnecessary `new` in require statement

### PR DESCRIPTION
**Pull request by cameronhunter**
As suggested in issue #104. Also removing unnecessary `.js` suffixes.

### CODE REVIEW

**Comment by Hardmath123** [comment]
I don't see why we're omitting the `.js` — it doesn't make sense to me, and I'd rather keep the `.js` extensions unless there's an alarmingly urgent reason to omit them.

I'll merge just the `new` change if you PR that on its own.

**Comment by cameronhunter** [comment]
For context, I removed the `.js` suffixes because it isn't normal convention to specify it.

**Comment by Hardmath123** [comment]
Hmm, I'm not sure how I feel about that. I think I'll keep the `.js` extensions if that's alright with everyone.

**Comment by Hardmath123** [comment]
\o/ Thanks!

**Pull request merged**
