### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by tjvr**
This adds the "Please review the guidelines for contributing" warning to the New Issue page.

### CODE REVIEW

**Comment by tjvr** [comment]
@Hardmath123 You might want to re-word this. :)

**Comment by Hardmath123** [comment]
Yeah, I need to reword this — there are some other things I want in there. (I like how we can make an FAQ by filtering the issues, though. Clever!)

**Comment by tjvr** [comment]
> I like how we can make an FAQ by filtering the issues, though. Clever!

Thanks! It's not ideal (there are useful issues not tagged question) but I feel gets the point across better than "please search before creating a new issue" would. :)

**Comment by Hardmath123** [comment]
I tried to make it a little more thorough.

**Pull request merged**
