### PR TITLE
Added grammar for COOL recursive comments

### PR DESCRIPTION
**Pull request by vietlq**
Grammar for parsing content of recursive comments of COOL (The Classroom Object-Oriented Language)

* Treat everything inside the outmost (**) as content
* Empty comment: `(**)`
* Recursive comments: `(*(**)*)` => `(**)`, `(*(*a*)(*b*)*)` => `(*a*)(*b*)`
* Invalid comments: `(*)*)`, `(*(*)`, `(*(**)`, `(*(*)*)`
* For details, check: http://theory.stanford.edu/~aiken/software/cool/cool.html

### CODE REVIEW

**Comment by Hardmath123** [comment]
I'm happy to merge the grammar, but I'm iffy about merging the test.

How much value do you think this additional test adds? I'm all for more tests, but I feel they should test orthogonal features rather than re-testing features that are already tested. (cc @tjvr)

Also, @vietlq, I feel we should prefer example parsers for well-known languages over academic examples. This is partly because it is easier for people to understand examples of languages they already know, and partly because an example parser for a real-world language might someday be useful for someone! :-)

**Comment by vietlq** [comment]
Then I should rename to: OCaml nested comments

https://ocaml.org/learn/tutorials/basics.html#Comments

Also add some files to test the code. Sounds good? Not academic anymore.

**Comment by vietlq** [comment]
I would appreciate an example how to improve the tests

**Comment by vietlq** [comment]
I will reserve this for a newbie's tutorial.

**Pull request closed without merging**
